# Generated by Django 4.2.3 on 2023-07-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('title', models.CharField(choices=[('Team Lead', 'LEAD'), ('Mid Lead', 'MID'), ('Junior', 'JUN')], max_length=15)),
                ('gender', models.CharField(choices=[('Female', 'F'), ('Male', 'M'), ('Other', 'O'), ('Prefer Not Say', 'N')], max_length=20)),
                ('salary', models.PositiveIntegerField(default=30000)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('departman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personels', to='personel.departman')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
