# Generated by Django 4.2.2 on 2023-06-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
    ]
